data:
  train_raw: "/home/sunesh/NLP/Multi_Label_Toxic_Comment_Classifier/Dataset/train.csv"
  test_raw: "/home/sunesh/NLP/Multi_Label_Toxic_Comment_Classifier/Dataset/test.csv"
  train_preprocessed: "/home/sunesh/NLP/Multi_Label_Toxic_Comment_Classifier/Dataset/Ekphrasis_processed/train_preprocessed.csv"
  test_preprocessed: "/home/sunesh/NLP/Multi_Label_Toxic_Comment_Classifier/Dataset/Ekphrasis_processed/test_preprocessed.csv"
  train_tokens: "/home/sunesh/NLP/Multi_Label_Toxic_Comment_Classifier/Dataset/Ekphrasis_processed/train_tokens.pkl"
  test_tokens: "/home/sunesh/NLP/Multi_Label_Toxic_Comment_Classifier/Dataset/Ekphrasis_processed/test_tokens.pkl"
  train_tokens_sample: "/home/sunesh/NLP/Multi_Label_Toxic_Comment_Classifier/Dataset/Ekphrasis_processed/train_tokens_sample.json"
results:
  optuna_vectorizer_allmodel_results: /home/sunesh/NLP/Multi_Label_Toxic_Comment_Classifier/results/optuna_vectorizer_allmodel_results.csv